#!/usr/bin/env python3
"""U6: deterministic model and channel cost per practitioner per month.

Reads inputs.json next to this file and prints Markdown tables to stdout.
No randomness, no network. Every input carries a SOURCE / SECONDARY /
ASSUMPTION / OWNER label in inputs.json; this code only applies formulas.

Run from the repository root:
    python -B models/U6-UNIT-COST/u6_model.py > models/U6-UNIT-COST/results.md
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
MTOK = 1_000_000


def load_inputs(path: Path = HERE / "inputs.json") -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def monthly_tokens(p: dict) -> dict:
    """Monthly token volumes in reference-tokenizer tokens, before tokenizer factor and overhead.

    Per dialog with n client messages, t tool calls and escalation share e:
      reply call i (1..n) input  = P + C + (i-1)*E + E/2   -> sum = n*P + n*C + E*n^2/2
      tool call input            = P + C + n*E/2 + TR      (t calls)
      card update input          = A + C + n*E             (1 call)
      escalation summary input   = A + C + n*E             (e calls on average)
    where P = system + kb + tools (static, cacheable), A = aux instruction.
    """
    dialogs = p["visits_per_month"] * p["dialogs_per_visit"]
    n = p["client_msgs_per_dialog"]
    t = p["tool_calls_per_dialog"]
    e = p["escalation_share"]
    static_prefix = p["system_tokens"] + p["kb_tokens"] + p["tools_tokens"]
    card = p["card_tokens"]
    exch = p["exchange_tokens"]
    transcript = n * exch

    static_per_dialog = (n + t) * static_prefix
    dynamic_per_dialog = (
        n * card + exch * n * n / 2
        + t * (card + transcript / 2 + p["tool_result_tokens"])
        + (1 + e) * (p["aux_instruction_tokens"] + card + transcript)
    )
    output_per_dialog = (
        n * p["output_tokens_per_reply"]
        + t * p["output_tokens_per_tool_call"]
        + p["card_update_output_tokens"]
        + e * p["escalation_output_tokens"]
    )
    return {
        "dialogs": dialogs,
        "model_calls": dialogs * (n + t + 1 + e),
        "agent_replies": dialogs * n,
        "static_input": dialogs * static_per_dialog,
        "dynamic_input": dialogs * dynamic_per_dialog,
        "output": dialogs * output_per_dialog,
    }


def model_cost(p: dict, price: dict, cached: bool) -> float:
    """Monthly model cost in USD for one practitioner."""
    tok = monthly_tokens(p)
    scale = price["tokenizer_factor"] * p["overhead_multiplier"] / MTOK
    if cached:
        h = p["cache_hit_rate"]
        static_rate = h * price["cache_read"] + (1 - h) * price["cache_write_1h"]
    else:
        static_rate = price["input"]
    usd = (
        tok["static_input"] * static_rate
        + tok["dynamic_input"] * price["input"]
        + tok["output"] * price["output"]
    )
    return usd * scale


def whatsapp_cost(p: dict, template_rate: float, reply_rate: float) -> float:
    reminders = p["visits_per_month"] * p["reminders_per_visit"]
    replies = monthly_tokens(p)["agent_replies"]
    return reminders * template_rate + replies * reply_rate


def onboarding_cost(onb: dict, price: dict) -> float:
    f = price["tokenizer_factor"]
    return f * (onb["input_tokens"] * price["input"] + onb["output_tokens"] * price["output"]) / MTOK


def fmt(x: float) -> str:
    return f"{x:,.2f}"


def render(inputs: dict) -> str:
    models = inputs["model_prices"]["models"]
    scenarios = inputs["scenarios"]
    ch = inputs["channels"]
    tg_business = ch["telegram_business_monthly"]["value"]
    tpl = ch["whatsapp_utility_template"]["values"]
    rep = ch["whatsapp_service_reply"]["values"]
    points = inputs["price_points"]["values"]
    out: list[str] = []
    w = out.append

    w("# U6 results (generated)")
    w("")
    w("Generated by `models/U6-UNIT-COST/u6_model.py` from `models/U6-UNIT-COST/inputs.json`. "
      "Do not edit by hand; change inputs and re-run. USD per practitioner per month unless stated. "
      "Framing, labels and limitations: `models/U6-UNIT-COST/README.md`.")
    w("")

    w("## 1. Volume implied by each scenario")
    w("")
    w("| Scenario | Visits | Dialogs | Agent replies | Model calls | Static input, M tok | Dynamic input, M tok | Output, M tok |")
    w("| --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: |")
    for name, p in scenarios.items():
        t = monthly_tokens(p)
        w(f"| {name} | {p['visits_per_month']} | {t['dialogs']:,.0f} | {t['agent_replies']:,.0f} | {t['model_calls']:,.0f} "
          f"| {t['static_input'] / MTOK:,.2f} | {t['dynamic_input'] / MTOK:,.2f} | {t['output'] / MTOK:,.2f} |")
    w("")
    w("Token volumes are in the reference (Haiku 4.5) tokenizer, before the tokenizer factor and the overhead multiplier.")
    w("")

    w("## 2. Model cost per month")
    w("")
    w("| Scenario | Model | No caching | 1h cache on static prefix |")
    w("| --- | --- | ---: | ---: |")
    for name, p in scenarios.items():
        for mid, price in models.items():
            w(f"| {name} | {mid} | {fmt(model_cost(p, price, False))} | {fmt(model_cost(p, price, True))} |")
    w("")

    w("## 3. Channel cost per month")
    w("")
    w("| Scenario | Telegram Bot API | Telegram Business (assumed subscription) | WhatsApp: templates only, base rate | WhatsApp: templates base + replies at 0.002 | WhatsApp: templates high + replies at 0.005 |")
    w("| --- | ---: | ---: | ---: | ---: | ---: |")
    for name, p in scenarios.items():
        w(f"| {name} | 0.00 | {fmt(tg_business)} | {fmt(whatsapp_cost(p, tpl['base'], rep['zero']))} "
          f"| {fmt(whatsapp_cost(p, tpl['base'], rep['hyp_0_002']))} | {fmt(whatsapp_cost(p, tpl['high'], rep['hyp_0_005']))} |")
    w("")
    w("Reply rates 0.002 and 0.005 USD are hypothetical sensitivity points, not published rates.")
    w("")

    w("## 4. Model + channel as a share of reference price points (Telegram Bot API, 1h cache)")
    w("")
    header = " | ".join(f"${x}" for x in points)
    w(f"| Scenario | Model | Cost | {header} |")
    w("| --- | --- | ---: | " + " | ".join("---:" for _ in points) + " |")
    for name, p in scenarios.items():
        for mid, price in models.items():
            c = model_cost(p, price, True)
            shares = " | ".join(f"{100 * c / x:.1f}%" for x in points)
            w(f"| {name} | {mid} | {fmt(c)} | {shares} |")
    w("")
    w("Upper bound without caching and with Telegram Business subscription, same price points:")
    w("")
    w(f"| Scenario | Model | Cost | {header} |")
    w("| --- | --- | ---: | " + " | ".join("---:" for _ in points) + " |")
    for name, p in scenarios.items():
        for mid, price in models.items():
            c = model_cost(p, price, False) + tg_business
            shares = " | ".join(f"{100 * c / x:.1f}%" for x in points)
            w(f"| {name} | {mid} | {fmt(c)} | {shares} |")
    w("")

    w("## 5. One-at-a-time sensitivity (base scenario, claude-sonnet-5, 1h cache)")
    w("")
    base = scenarios["base"]
    ref_price = models["claude-sonnet-5"]
    ref = model_cost(base, ref_price, True)
    w(f"Base cost: {fmt(ref)}. Each row moves one parameter to its low / high scenario value, others at base.")
    w("")
    w("| Parameter | Low value | Cost at low | High value | Cost at high | Swing |")
    w("| --- | ---: | ---: | ---: | ---: | ---: |")
    rows = []
    for key in base:
        lo_v, hi_v = scenarios["low"][key], scenarios["high"][key]
        if lo_v == hi_v or key == "reminders_per_visit":
            continue
        lo_c = model_cost({**base, key: lo_v}, ref_price, True)
        hi_c = model_cost({**base, key: hi_v}, ref_price, True)
        rows.append((abs(hi_c - lo_c), key, lo_v, lo_c, hi_v, hi_c))
    for swing, key, lo_v, lo_c, hi_v, hi_c in sorted(rows, reverse=True):
        w(f"| {key} | {lo_v} | {fmt(lo_c)} | {hi_v} | {fmt(hi_c)} | {fmt(swing)} |")
    w("")

    w("## 6. One-off onboarding per practitioner")
    w("")
    onb = inputs["onboarding_one_off"]
    w(f"Assumed {onb['input_tokens']:,} input and {onb['output_tokens']:,} output reference tokens, no caching.")
    w("")
    w("| Model | One-off cost |")
    w("| --- | ---: |")
    for mid, price in models.items():
        w(f"| {mid} | {fmt(onboarding_cost(onb, price))} |")
    w("")
    return "\n".join(out)


def main() -> int:
    sys.stdout.write(render(load_inputs()))
    return 0


if __name__ == "__main__":
    sys.exit(main())
